version: "3"
services:
    app:
        build: .
        working_dir: /var/www/html
        command: ["php-fpm"]  # Ensure this starts PHP-FPM in the foreground
        environment:
            MONGODB_URI: 'mongodb://mongodb/'
        volumes:
            - .:/var/www/html
        depends_on:
            mongodb:
                condition: service_healthy
        networks:
            - laravel

    web:
        image: "nginx:latest"
        ports:
            - "80:80"
        volumes:
            - ./docker-compose/nginx/:/etc/nginx/conf.d/
            - .:/var/www/html
        depends_on:
            - app
        networks:
            - laravel

    mongodb:
        image: mongo
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: example
        ports:
            - 27017:27017
        healthcheck:
            test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
        networks:
            - laravel

    mongo-express:
        image: mongo-express
        restart: always
        ports:
            - 8081:8081
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: root
            ME_CONFIG_MONGODB_ADMINPASSWORD: example
            ME_CONFIG_MONGODB_SERVER: mongodb
            ME_CONFIG_BASICAUTH: false
        networks:
            - laravel

networks:
    laravel:
